<template>
    <v-container class="pa-md-10">
        <h1 class="font-weight-bold grey--text display-1 pl-3 my-5">SKILLS</h1>
        <div class="d-flex flex-row justify-start flex-wrap">
            <v-img 
            class="ma-4"
                contain
                height="80"
                width="80"
                max-width="80"
                src="@/assets/flutter.png">
            </v-img>
            <v-img 
            class="ma-4"
                contain
                height="80"
                width="80"
                max-width="80"
                src="@/assets/vuejs.png">
            </v-img>
            <v-img 
            class="ma-4"
                contain
                height="80"
                width="80"
                max-width="80"
                src="@/assets/firebase.png">
            </v-img>
            <v-img 
            class="ma-4"
                contain
                height="80"
                width="80"
                max-width="80"
                src="@/assets/java.png">
            </v-img>
            <v-img 
            class="ma-4"
                contain
                height="80"
                width="80"
                max-width="80"
                src="@/assets/python.png">
            </v-img>
            <v-img 
            class="ma-4"
                contain
                height="80"
                width="80"
                max-width="80"
                src="@/assets/html.png">
            </v-img>
            <v-img
            class="ma-4" 
                contain
                height="80"
                width="80"
                max-width="80"
                src="@/assets/css.png">
            </v-img>
            <v-img
            class="ma-4" 
                contain
                height="80"
                width="80"
                max-width="80"
                src="@/assets/javascript.png">
            </v-img>
            <v-img
            class="ma-4" 
                contain
                height="80"
                width="80"
                max-width="80"
                src="@/assets/c.png">
            </v-img>
            <v-img 
            class="ma-4"
                contain
                height="80"
                width="80"
                max-width="80"
                src="@/assets/git.png">
            </v-img>
            <v-img 
            class="ma-4"
                contain
                height="80"
                width="80"
                max-width="80"
                src="@/assets/android.png">
            </v-img>
            <v-img 
            class="ma-4"
                contain
                height="80"
                width="80"
                max-width="80"
                src="@/assets/sql.png">
            </v-img>
            <v-img 
            class="ma-4"
                contain
                height="80"
                width="80"
                max-width="80"
                src="@/assets/phpmyadmin.png">
            </v-img>
            <v-img 
            class="ma-4"
                contain
                height="80"
                width="80"
                max-width="80"
                src="@/assets/opencv.png">
            </v-img>
            <v-img 
            class="ma-4"
                contain
                height="80"
                width="80"
                max-width="80"
                src="@/assets/flask.png">
            </v-img>
            <v-img 
            class="ma-4"
                contain
                height="80"
                width="80"
                max-width="80"
                src="@/assets/xampp.png">
            </v-img>
            <v-img 
            class="ma-4"
                contain
                height="80"
                width="80"
                max-width="80"
                src="@/assets/powerbi.jpg">
            </v-img>
            <v-img 
            class="ma-4"
                contain
                height="80"
                width="80"
                max-width="80"
                src="@/assets/keras.png">
            </v-img>
            <v-img 
            class="ma-4"
                contain
                height="80"
                width="80"
                max-width="80"
                src="@/assets/adobe-photoshop.png">
            </v-img>
            <v-img 
            class="ma-4"
                contain
                height="80"
                width="80"
                max-width="80"
                src="@/assets/adobe-premiere-pro.png">
            </v-img>
        </div>
        <h3 class="pt-5 green--text justify-center">And the learning continues...</h3>
    </v-container>
</template>

<script>
export default {
    name: "Skills",
    data(){
        return {
            
        }
    }
}
</script>